services:

  django_gunicorn:
    build:
      context: ./app
    env_file:
      - ./.env
    environment:
      - ENV=development
    volumes: 
      - static_volume:/home/eugene/static/
      - db_volume:/home/eugene/db/
    ports:
      - "8008:8008"

  nginx:
    build:
      context: ./nginx_dev
    env_file:
      - ./.env

    environment:
      - ENV=development
    volumes: 
      - static_volume:/home/eugene/static/
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static_volume:
  db_volume:
    driver: local
    driver_opts:
      type: none
      device: ./db
      o: bind
